sudo: false
language: java
cache:
  directories:
    - $HOME/.m2
env:
  global:
    - DISPLAY=:99.0
before_install:
  - sh -e /etc/init.d/xvfb start - sleep 10
script:
- cd lionengine-parent
- jdk_switcher use oraclejdk8
- mvn clean install -Pcore
- mvn clean install -Ptests
- mvn clean verify -Pplugins
- mvn clean verify -Ptests-plugins
