sudo: false
language: java
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.m2
env:
  global:
    - DISPLAY=:99.0
before_install:
  - sh -e /etc/init.d/xvfb start - sleep 10
script:
- cd lionengine-parent
- mvn clean install -Pcore -Dcheckstyle.skip=true
- mvn clean verify -Pplugins -Dcheckstyle.skip=true
- mvn clean install -Pexamples -Dcheckstyle.skip=true
- mvn clean install -Ptutorials -Dcheckstyle.skip=true
- mvn clean verify -Peditor -Dcheckstyle.skip=true
